apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodeclasses.rebalancer.dev
spec:
  group: rebalancer.dev
  scope: Cluster
  names:
    plural: nodeclasses
    singular: nodeclass
    kind: NodeClass
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                matchLabels:
                  type: object
                  additionalProperties:
                    type: string
                matchExpressions:
                  type: array
                  items:
                    type: object
                    required:
                      - key
                      - operator
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      values:
                        type: array
                        items:
                          type: string
                preferredFor:
                  type: array
                  items:
                    type: string
                weight:
                  type: integer
                  format: int32
            status:
              type: object
              properties:
                nodeCount:
                  type: integer
                  format: int32
                lastSync:
                  type: string
                  format: date-time
      subresources:
        status: {}
