apiVersion: batch/v1
kind: Job
metadata:
  name: trivy-scan
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: trivy
          image: aquasec/trivy:latest
          args:
            [
              "image",
              "--severity",
              "HIGH,CRITICAL",
              "--no-progress",
              "__IMAGE_DEST__"
            ]

