apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rebalancer.fullname" . }}
  labels:
    {{- include "rebalancer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rebalancer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rebalancer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "rebalancer.serviceAccountName" . }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --metrics-bind-address=:{{ .Values.metrics.service.port }}
            - --health-probe-bind-address=:8081
            - --leader-elect={{ .Values.leaderElection }}
            - --prometheus-address={{ .Values.metrics.prometheusAddress }}
            - --emptydir-threshold-gi={{ .Values.policy.emptyDirThresholdGi }}
          ports:
            - containerPort: {{ .Values.metrics.service.port }}
              name: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
{{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
{{- end }}
