{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rebalancer.fullname" . }}
  labels:
    {{- include "rebalancer.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "rebalancer.fullname" $ }}
                port:
                  number: {{ $.Values.metrics.service.port }}
    {{- end }}
{{- end }}
